## Copy()

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we use this syntax we would be working the copy and the original.

In [3]:
#arr_slice = arr[0:6]
#arr_slice[:] = 0
#arr_slice


Best practice is to use copy()

In [4]:
arr_copy=  arr.copy()
arr_copy[:] =100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [5]:
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8af9fde7-6d07-4638-8fef-c27d1b3023f8' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>