## Conditions

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
ind_contitions = arr > 5
ind_contitions

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Array condition

In [4]:
arr[ind_contitions] #arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

Multiple conditions 

In [5]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

Modify an array through a condition

In [6]:
arr[arr >5] = 12
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12, 12, 12], dtype=int8)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8af9fde7-6d07-4638-8fef-c27d1b3023f8' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>