## 

In [1]:
import numpy as np

In [2]:
my_list = [1,2]
my_list

[1, 2]

Vanilla python 

In [3]:
my_list * 2

[1, 2, 1, 2]

Using numpy

In [4]:
second_list = np.arange(0,10)
print(second_list * 2)
print(second_list + 2)
print(second_list / 2)
print(second_list ** 2)


[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [5]:
matrix = second_list.reshape(2,5)
matrix2 = matrix.copy()

In [6]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [7]:
np.matmul(matrix,matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [8]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8af9fde7-6d07-4638-8fef-c27d1b3023f8' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>