# Data types

In [1]:
import numpy as np

int64

In [3]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

int64 to float64

In [27]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype
arr

array([1., 2., 3., 4.])

int64 to float64 using numpy astype

In [28]:
second_array = np.array([1,2,3,4,5])
second_array
second_array.astype(np.float64)

array([1., 2., 3., 4., 5.])

int64 to bool_

In [23]:
third_array = np.array([0,1,2,3,4,5])
third_array.astype(np.bool_)

array([False,  True,  True,  True,  True,  True])

int64 to string_

In [24]:
fourth_array = np.array([0,1,2,3,4,5])
fourth_array.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

string to int8

In [25]:
fifth_array = np.array(['0','1','2',])
fifth_array.astype(np.int8)

array([0, 1, 2], dtype=int8)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a078f44d-eb2b-4225-8fa4-104fee096f2f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>