# Dimensions 

In [1]:
import numpy as np

### Scalar

In [2]:
scalar = np.array(42)
print(f"Value: ", scalar)
print(f"Dimensions: ", scalar.ndim)

Value:  42
Dimensions:  0


### Vector

In [3]:
vector = np.array([1,2,3,4,5])
print(f"Value: ", vector)
print(f"Dimensions: ", vector.ndim)

Value:  [1 2 3 4 5]
Dimensions:  1


### Matrix

In [4]:
matrix = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(f"Value:\n", matrix)
print(f"Dimensions: ", matrix.ndim)

Value:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Dimensions:  2


### Tensor

In [5]:
tensor = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(f"Value:\n", tensor)
print(f"Dimensions: ", tensor.ndim)

Value:
 [[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
Dimensions:  3


## Add or remove dimensions

Adding dimensions from the definition

In [6]:
vector = np.array([1,2,3,4,5], ndmin=10)
print(f"Value: ", vector)
print(f"Dimensions: ", vector.ndim)

Value:  [[[[[[[[[[1 2 3 4 5]]]]]]]]]]
Dimensions:  10


Add dimensions using expand_dims

In [7]:
expand = np.expand_dims(np.array([1,2,3]), axis= 0)
print(f"Value: ", expand)
print(f"Dimensions: ", expand.ndim)

Value:  [[1 2 3]]
Dimensions:  2


Remove dimension that aren't in use using squeeze

In [8]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]] 10
[1 2 3 4 5]


Challenge:

- Write a 5 dimensions tensor

- Add a dimension

- Delete unused dimensions 

In [9]:
#Write a 5 dimensions tensor
tens_challenge = np.array([[[1,2,3],[4,5,6]],
                           [[7,8,9],[10,11,12]],
                            [[13,14,15],[16,17,18]]], ndmin=5)

print(tens_challenge)
print(f"Dimensions: {tens_challenge.ndim}")

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]

   [[13 14 15]
    [16 17 18]]]]]
Dimensions: 5


In [10]:
#Add a dimension

tens_challenge = np.expand_dims(tens_challenge, axis=0)
print(tens_challenge)
print(f"Dimensions: {tens_challenge.ndim}")

[[[[[[ 1  2  3]
     [ 4  5  6]]

    [[ 7  8  9]
     [10 11 12]]

    [[13 14 15]
     [16 17 18]]]]]]
Dimensions: 6


In [11]:
#Delete unused dimensions 
tens_challenge = np.squeeze(tens_challenge)
print(tens_challenge)
print(f"Dimensions: {tens_challenge.ndim}")conda 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Dimensions: 3


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=75a4f858-41e2-447c-aecc-2e392fdc3531' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>