In [5]:
import numpy as np
l1 = list(range(0,10))
print(l1, type(l1))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [6]:
l2 = np.arange(0,10)
print(l2, type(l2))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [7]:
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(4)

array([0.63127942, 0.36577277, 0.93906849, 0.90566428])

In [16]:
np.random.rand(4,4)

array([[0.1920369 , 0.92615557, 0.01503511, 0.70584922],
       [0.83350619, 0.31564245, 0.13245983, 0.40787663],
       [0.80953356, 0.80995736, 0.88944601, 0.76118386],
       [0.85730052, 0.37987883, 0.96940652, 0.40724371]])

In [18]:
np.random.randint(1,15)

9

In [19]:
np.random.randint(1,100,(10,10))

array([[13, 13, 22, 84, 15, 28, 20, 88, 65, 91],
       [79, 43, 36, 23, 56, 44, 26, 36, 72, 36],
       [86, 73, 75, 21, 84,  5, 67, 91, 85, 93],
       [95,  2, 43, 37, 63, 77, 91, 98, 36, 88],
       [24,  7, 23, 84, 34, 10, 76, 36, 36, 29],
       [70, 83, 71, 85, 58, 18, 90, 83, 13, 32],
       [35, 33, 77, 24, 35, 63, 56, 86, 99, 27],
       [77, 77, 72, 46, 79,  1,  7, 81, 76, 43],
       [11, 17, 98, 64, 73, 24,  4, 50, 47, 70],
       [83,  4, 64, 79, 16, 84, 96, 89, 92, 55]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=09878c07-e45a-421c-bea7-be05b23d49d9' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>