### Shape and Reshape

In [1]:
import numpy as np

Generates an array with random integers

In [2]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape

[[4 1]
 [7 3]
 [2 4]]


(3, 2)

Reshape the original array 

In [3]:
arr.reshape(1,6)

array([[4, 1, 7, 3, 2, 4]])

In [4]:
arr.reshape(2,3)

array([[4, 1, 7],
       [3, 2, 4]])

In [5]:
np.reshape(arr,(6,1))

array([[4],
       [1],
       [7],
       [3],
       [2],
       [4]])

Reshape as 'C' language 

In [6]:
np.reshape(arr,(2,3),'C')

array([[4, 1, 7],
       [3, 2, 4]])

Reshape as 'Fortran' language 

In [7]:
np.reshape(arr,(2,3),'F')

array([[4, 2, 3],
       [7, 1, 4]])

Reshape as randomly, optimized as memory does it 

In [8]:
np.reshape(arr,(2,3),'A')

array([[4, 1, 7],
       [3, 2, 4]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e7ca1efc-2266-4a9c-b63d-81ff62e08669' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>