# Functions

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)
arr

array([ 8,  6,  2,  3,  2,  2, 12,  1,  8, 13])

In [3]:
matrix = arr.reshape(2,5)
matrix

array([[ 8,  6,  2,  3,  2],
       [ 2, 12,  1,  8, 13]])

### max() and min()

In [4]:
arr.max()


13

In [5]:
print(matrix.max())
#max number of axis one
print(matrix.max(1))
#max number of axis zero
print(matrix.max(0))
#index of the max number, if there are more than one, it selects the lower
print(matrix.argmax(0))

13
[ 8 13]
[ 8 12  2  8 13]
[0 1 0 1 1]


In [6]:
print(matrix.min())
#min number of axis one
print(matrix.min(1))
#min number of axis zero
print(matrix.min(0))
#index of the min number, if there are more than one, it selects the lower
print(matrix.argmin(0))


1
[2 1]
[2 6 1 3 2]
[1 0 1 0 0]


### PTP (peak to peak)

In [7]:
#Difference betwen the greater and lower value
arr.ptp()
#Difference betwen the greater and lower value in 0 axis
arr.ptp(0)

12

### Percentile, sort, median, mean  variance and std

In [15]:
#sorted array
print(np.sort(arr))
#Higher
print(np.percentile(arr,100))
#median
print(np.percentile(arr,50))
print(np.median(arr))
#median matrix
print(np.median(matrix,1))
#stanrdard deviation
print(np.std(arr))
#variance
print(np.var(arr))
#mean
print(np.mean(arr))

[ 1  2  2  2  3  6  8  8 12 13]
13.0
4.5
4.5
[3. 8.]
4.172529209005013
17.41
5.7


### Concatenate

In [30]:
a = np.array([[1,2],[3,4]])
print(a, "\n")
b = np.array([5,6])
print(b,"\n")
b = np.expand_dims(b, axis=0)
print(b,"\n")
print(np.concatenate((a,b), axis=0), "\n")
print(np.concatenate((a,b.T), axis=1))

[[1 2]
 [3 4]] 

[5 6] 

[[5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=ddb606bf-6564-4efd-88d9-330d6dcfff3e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>